Repository hd-team4/dorakdorack-backend, pull requests merged in 2025-06, with the labels that each got.

#12 [#11] OCI 연결을 위한 의존성 추가
  Dockerfile
  build.gradle
Labels: 🌏 Deploy

#13 [#11] OCI 연결을 위한 의존성 추가 등
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/dorakdorak/global/config/ConfigExample.java
  src/main/java/dorakdorak/global/config/S3Config.java
  src/main/java/dorakdorak/global/error/ErrorCode.java
  src/main/java/dorakdorak/global/error/GlobalExceptionHandler.java
  src/main/java/dorakdorak/infra/file/FileService.java
  src/main/java/dorakdorak/infra/file/s3/S3Example.java
  src/main/java/dorakdorak/infra/file/s3/S3FileService.java
  src/main/resources/application.yml
  src/main/resources/mapper/Mapper.xml
  src/main/resources/static/test-dosirak-image.JPG
  src/test/java/dorakdorak/infra/file/s3/S3FileServiceTest.java
Labels: 🌏 Deploy

#17 [FIX] 주석때문에 컨테이너 안띄워지는 문제 수정
  .github/workflows/deploy.yml
Labels: 🐛 Bug

#22 [#18] 도시락 잔량 분석 기능 추가
  build.gradle
  src/main/java/dorakdorak/global/error/ErrorCode.java
  src/main/java/dorakdorak/infra/openai/OpenAiVisionClient.java
  src/main/java/dorakdorak/infra/openai/dto/OpenAiResponse.java
  src/main/java/dorakdorak/infra/openai/exception/OpenAiVisionException.java
  src/test/java/dorakdorak/infra/openai/OpenAiVisionClientTest.java
Labels: ✨ Feature

#25 [#23] QR 인증 토큰 발급 및 검증 기능 구현
  build.gradle
  src/main/java/dorakdorak/global/error/ErrorCode.java
  src/main/java/dorakdorak/global/util/UtilExample.java
  src/main/java/dorakdorak/global/util/jwt/JwtUtil.java
  src/main/java/dorakdorak/global/util/jwt/QrTokenProvider.java
  src/test/java/dorakdorak/global/util/jwt/QrTokenProviderTest.java
Labels: ✨ Feature

#31 [#30] Swagger 환경 설정
  build.gradle
  src/main/java/dorakdorak/global/config/SecurityConfig.java
  src/main/java/dorakdorak/global/config/SwaggerConfig.java
Labels: ⚙️ Setting

#34 [#32] build.gradle 수정
  build.gradle
Labels: 🛠️ Refactor

#37 [#번호없음] cicd workflow 수정
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#40 [#번호없음] cicd 사소한 오류 수정 & 로그인 API 반영
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/dorakdorak/domain/member/api/MemberController.java
  src/main/java/dorakdorak/domain/member/dto/request/MemberLoginRequest.java
  src/main/java/dorakdorak/domain/member/dto/response/MemberLoginResponse.java
Labels: 🐛 Bug, 🌏 Deploy

#44 [#번호없음] 스웨거 CORS 문제 수정
  src/main/java/dorakdorak/global/config/CorsConfig.java
  src/main/resources/application.yml
Labels: 🐛 Bug

#47 [#번호없음] 스웨거 설정 수정
  src/main/java/dorakdorak/domain/auth/api/AuthController.java
  src/main/java/dorakdorak/domain/auth/api/ReissueController.java
  src/main/java/dorakdorak/domain/auth/dto/response/CustomMemberDetails.java
  src/main/java/dorakdorak/domain/auth/dto/response/MemberAuthDto.java
  src/main/java/dorakdorak/domain/auth/filter/LoginFilter.java
  src/main/java/dorakdorak/domain/auth/jwt/JWTFilter.java
  src/main/java/dorakdorak/domain/auth/jwt/JWTUtil.java
  src/main/java/dorakdorak/global/config/SwaggerConfig.java
  src/main/resources/application.yml
  src/main/resources/mapper/MemberMapper.xml
Labels: 🐛 Bug

#49 [#번호없음] CICD 수정
  .github/workflows/deploy.yml
  src/main/java/dorakdorak/domain/zeroWaste/service/DosirakRemainAnalyzer.java
  src/main/java/dorakdorak/global/error/ErrorCode.java
  src/main/java/dorakdorak/infra/openai/OpenAiVisionClient.java
  src/main/java/dorakdorak/infra/openai/exception/OpenAiVisionException.java
  src/test/java/dorakdorak/infra/openai/OpenAiVisionClientTest.java
Labels: 🐛 Bug

#50 [CHORE] CORS 수정
  src/main/java/dorakdorak/domain/auth/api/ReissueController.java
  src/main/java/dorakdorak/domain/auth/filter/LoginFilter.java
  src/main/java/dorakdorak/global/config/SecurityConfig.java
Labels: 🐛 Bug

#56 [#2] 도시락 주문 및 결제 구현
  build.gradle
  src/main/java/dorakdorak/domain/admin/api/AdminController.java
  src/main/java/dorakdorak/domain/dosirak/dto/response/DosirakOrderDto.java
  src/main/java/dorakdorak/domain/order/api/OrderController.java
  src/main/java/dorakdorak/domain/order/dto/AdminOrderDto.java
  src/main/java/dorakdorak/domain/order/dto/GroupOrderDto.java
  src/main/java/dorakdorak/domain/order/dto/OrderDto.java
  src/main/java/dorakdorak/domain/order/dto/OrderItemDto.java
  src/main/java/dorakdorak/domain/order/dto/request/OrderRequestDto.java
  src/main/java/dorakdorak/domain/order/dto/request/OrderStatusUpdateRequest.java
  src/main/java/dorakdorak/domain/order/dto/response/AdminOrderListResponse.java
  src/main/java/dorakdorak/domain/order/dto/response/GroupOrderListResponse.java
  src/main/java/dorakdorak/domain/order/enums/OrderStatus.java
  src/main/java/dorakdorak/domain/order/enums/OrderType.java
  src/main/java/dorakdorak/domain/order/mapper/OrderMapper.java
  src/main/java/dorakdorak/domain/order/service/OrderService.java
  src/main/java/dorakdorak/domain/order/service/OrderServiceImpl.java
  src/main/java/dorakdorak/domain/payment/api/PaymentController.java
  src/main/java/dorakdorak/domain/payment/dto/request/GroupPaymentRequest.java
  src/main/java/dorakdorak/domain/payment/dto/request/OrderItemRequest.java
  src/main/java/dorakdorak/domain/payment/dto/request/PaymentConfirmRequest.java
  src/main/java/dorakdorak/domain/payment/dto/request/PaymentRequestDto.java
  src/main/java/dorakdorak/domain/payment/dto/request/SinglePaymentRequest.java
  src/main/java/dorakdorak/domain/payment/dto/response/PaymentPrepareResponse.java
  src/main/java/dorakdorak/domain/payment/dto/response/PaymentResponseDto.java
  src/main/java/dorakdorak/domain/payment/service/PaymentService.java
  src/main/java/dorakdorak/domain/payment/service/PaymentServiceImpl.java
  src/main/java/dorakdorak/global/error/ErrorCode.java
  src/main/java/dorakdorak/infra/file/MemoryMultipartFile.java
  src/main/java/dorakdorak/infra/payment/toss/TossErrorResponse.java
  src/main/java/dorakdorak/infra/payment/toss/TossPaymentsClient.java
  src/main/java/dorakdorak/infra/payment/toss/TossPaymentsResponse.java
  src/main/java/dorakdorak/infra/qrcode/QrCodeGenerator.java
  src/main/java/dorakdorak/infra/qrcode/QrCodeUploader.java
  src/main/resources/mapper/DosirakMapper.xml
  src/main/resources/mapper/OrderMapper.xml
Labels: ✨ Feature

#59 [#28] 커스텀 도시락 생성을 위한 dall-e API 연동
  src/main/java/dorakdorak/domain/dosirak/api/CustomDosirakController.java
  src/main/java/dorakdorak/domain/dosirak/dto/DosirakGenerationResultDto.java
  src/main/java/dorakdorak/domain/dosirak/dto/NutritionDto.java
  src/main/java/dorakdorak/domain/dosirak/dto/request/CustomDosirakPreviewRequest.java
  src/main/java/dorakdorak/domain/dosirak/dto/response/CustomDosirakPreviewResponse.java
  src/main/java/dorakdorak/domain/dosirak/service/DosirakPromptGenerator.java
  src/main/java/dorakdorak/domain/member/dto/MemberAllergyDto.java
  src/main/java/dorakdorak/domain/member/mapper/MemberMapper.java
  src/main/java/dorakdorak/domain/member/service/MemberService.java
  src/main/java/dorakdorak/domain/member/service/MemberServiceImpl.java
  src/main/java/dorakdorak/global/config/SecurityConfig.java
  src/main/java/dorakdorak/global/error/ErrorCode.java
  src/main/java/dorakdorak/infra/openai/OpenAiVisionClient.java
  src/main/resources/application.yml
  src/main/resources/mapper/MemberMapper.xml
  src/test/java/dorakdorak/DorakdorakApplicationTests.java
  src/test/java/dorakdorak/infra/openai/DosirakPromptGeneratorTest.java
Labels: ✨ Feature

#64 [FEAT] 대학별 제로웨이스트 랭킹 조회 api
  src/main/java/dorakdorak/domain/zeroWaste/api/ZeroWasteController.java
  src/main/java/dorakdorak/domain/zeroWaste/mapper/ZeroWasteMapper.java
  src/main/java/dorakdorak/domain/zeroWaste/service/ZeroWasteService.java
  src/main/java/dorakdorak/domain/zeroWaste/service/ZeroWasteServiceImpl.java
  src/main/java/dorakdorak/global/error/ErrorCode.java
  src/main/resources/mapper/ZeroWasteMapper.xml
Labels: ✨ Feature

#70 [#67] 공동구매 주문마감 로직 구현
  src/main/java/dorakdorak/DorakdorakApplication.java
  src/main/java/dorakdorak/domain/order/enums/OrderStatus.java
  src/main/java/dorakdorak/domain/order/mapper/OrderMapper.java
  src/main/java/dorakdorak/global/scheduler/GonggooScheduler.java
  src/main/java/dorakdorak/global/scheduler/GonggooSchedulerService.java
  src/main/resources/mapper/OrderMapper.xml
Labels: ✨ Feature

#69 [#62] 커스텀 도시락 등록 구현
  src/main/java/dorakdorak/domain/dosirak/api/CustomDosirakController.java
  src/main/java/dorakdorak/domain/dosirak/dto/response/CustomDosirakVoteResponse.java
  src/main/java/dorakdorak/domain/dosirak/mapper/DosirakMapper.java
  src/main/java/dorakdorak/domain/dosirak/service/DosirakService.java
  src/main/java/dorakdorak/domain/dosirak/service/DosirakServiceImpl.java
  src/main/java/dorakdorak/global/error/ErrorCode.java
  src/main/resources/mapper/DosirakMapper.xml
Labels: ✨ Feature

#79 [#78] 백엔드 컨벤션 적용
  src/main/java/dorakdorak/domain/auth/api/AuthController.java
  src/main/java/dorakdorak/domain/auth/dto/response/LoginDto.java
  src/main/java/dorakdorak/domain/auth/dto/response/MemberAuthDto.java
  src/main/java/dorakdorak/domain/auth/service/CustomMemberDetailsService.java
  src/main/java/dorakdorak/domain/dosirak/mapper/DosirakMapper.java
  src/main/java/dorakdorak/domain/dosirak/service/DosirakServiceImpl.java
  src/main/java/dorakdorak/domain/member/dto/MemberSignupDto.java
  src/main/java/dorakdorak/domain/member/mapper/MemberMapper.java
  src/main/java/dorakdorak/domain/member/service/MemberService.java
  src/main/java/dorakdorak/domain/member/service/MemberServiceImpl.java
  src/main/resources/mapper/DosirakMapper.xml
  src/main/resources/mapper/MemberMapper.xml
Labels: 🛠️ Refactor

#83 [#82] 이메일 인증 로직 개선
  src/main/java/dorakdorak/domain/dosirak/service/DosirakPromptGenerator.java
  src/main/java/dorakdorak/domain/member/service/MailService.java
Labels: ✨ Feature

#93 [#81] Main 업데이트
  src/main/resources/mapper/DosirakMapper.xml
Labels: 🐛 Bug

#97 [#89] 커스텀 도시락 생성 프롬프트 수정
  src/main/java/dorakdorak/domain/dosirak/service/DosirakPromptGenerator.java
  src/main/java/dorakdorak/infra/openai/OpenAiVisionClient.java
Labels: ✨ Feature

#100 [#81] 도시락 상세페이지 오류 수정
  src/main/java/dorakdorak/domain/dosirak/service/DosirakPromptGenerator.java
  src/main/java/dorakdorak/infra/openai/OpenAiVisionClient.java
  src/main/resources/mapper/DosirakMapper.xml
Labels: 🐛 Bug

#110 [#81] 무한스크롤 적용을 위한 수정
  src/main/java/dorakdorak/domain/dosirak/dto/MyCustomDosirakDto.java
  src/main/java/dorakdorak/domain/dosirak/mapper/DosirakMapper.java
  src/main/resources/mapper/DosirakMapper.xml
  src/main/resources/mapper/OrderMapper.xml
Labels: ✨ Feature

#111 [#81] 무한스크롤 적용을 위한 수정 배포
  src/main/java/dorakdorak/domain/dosirak/dto/MyCustomDosirakDto.java
  src/main/java/dorakdorak/domain/dosirak/mapper/DosirakMapper.java
  src/main/resources/mapper/DosirakMapper.xml
  src/main/resources/mapper/OrderMapper.xml
Labels: ✨ Feature

#114 [#112] 결제 요청 API의 Response 변경
  src/main/java/dorakdorak/domain/payment/dto/response/PaymentPrepareResponse.java
  src/main/java/dorakdorak/domain/payment/service/PaymentServiceImpl.java
Labels: ✨ Feature

#116 [#113] 주문 알림에 RabbitMQ 적용
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/dorakdorak/domain/auth/api/AuthController.java
  src/main/java/dorakdorak/domain/member/service/OrderMailService.java
  src/main/java/dorakdorak/domain/order/dto/OrderMailInfoDto.java
  src/main/java/dorakdorak/domain/order/service/OrderServiceImpl.java
  src/main/java/dorakdorak/global/config/RabbitMQConfig.java
  src/main/java/dorakdorak/global/util/mail/OrderMailContentBuilder.java
  src/main/java/dorakdorak/infra/mail/consumer/OrderMailConsumer.java
  src/main/java/dorakdorak/infra/mail/dto/OrderMailMessage.java
  src/main/java/dorakdorak/infra/mail/producer/OrderMailProducer.java
  src/main/java/dorakdorak/infra/mail/service/MailSender.java
  src/main/java/dorakdorak/infra/mail/service/OrderMailSender.java
  src/main/java/dorakdorak/infra/mail/service/OrderMailService.java
  src/main/java/dorakdorak/infra/mail/service/VerificationMailSender.java
  src/main/java/dorakdorak/infra/mail/service/VerificationMailService.java
  src/main/resources/application.yml
  src/test/java/dorakdorak/domain/member/service/OrderMailServiceTest.java
  src/test/java/dorakdorak/infra/mail/service/OrderMailServiceTest.java
Labels: ✨ Feature

#117 [#113] RabbitMQ 적용 업데이트
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/dorakdorak/domain/auth/api/AuthController.java
  src/main/java/dorakdorak/domain/member/service/OrderMailService.java
  src/main/java/dorakdorak/domain/order/dto/OrderMailInfoDto.java
  src/main/java/dorakdorak/domain/order/service/OrderServiceImpl.java
  src/main/java/dorakdorak/domain/payment/dto/response/PaymentPrepareResponse.java
  src/main/java/dorakdorak/domain/payment/service/PaymentServiceImpl.java
  src/main/java/dorakdorak/global/config/RabbitMQConfig.java
  src/main/java/dorakdorak/global/util/mail/OrderMailContentBuilder.java
  src/main/java/dorakdorak/infra/mail/consumer/OrderMailConsumer.java
  src/main/java/dorakdorak/infra/mail/dto/OrderMailMessage.java
  src/main/java/dorakdorak/infra/mail/producer/OrderMailProducer.java
  src/main/java/dorakdorak/infra/mail/service/MailSender.java
  src/main/java/dorakdorak/infra/mail/service/OrderMailSender.java
  src/main/java/dorakdorak/infra/mail/service/OrderMailService.java
  src/main/java/dorakdorak/infra/mail/service/VerificationMailSender.java
  src/main/java/dorakdorak/infra/mail/service/VerificationMailService.java
  src/main/resources/application.yml
  src/test/java/dorakdorak/domain/member/service/OrderMailServiceTest.java
  src/test/java/dorakdorak/infra/mail/service/OrderMailServiceTest.java
Labels: ✨ Feature

#72 [#66] 어드민 통계 API 구현
  src/main/java/dorakdorak/domain/admin/api/AdminController.java
  src/main/java/dorakdorak/domain/admin/dto/StatisticPopularResponseDto.java
  src/main/java/dorakdorak/domain/admin/dto/StatisticsOrderResponseDto.java
  src/main/java/dorakdorak/domain/admin/dto/StatisticsSalesResponseDto.java
  src/main/java/dorakdorak/domain/admin/dto/response/StatisticPopularResponse.java
  src/main/java/dorakdorak/domain/admin/dto/response/StatisticsOrderResponse.java
  src/main/java/dorakdorak/domain/admin/dto/response/StatisticsSalesResponse.java
  src/main/java/dorakdorak/domain/admin/mapper/AdminMapper.java
  src/main/java/dorakdorak/domain/admin/service/AdminService.java
  src/main/java/dorakdorak/domain/admin/service/AdminServiceImpl.java
  src/main/resources/mapper/AdminMapper.xml
Labels: ✨ Feature

#131 [#124] 토큰 사용 여부 확인 로직 구현
  src/main/java/dorakdorak/domain/zeroWaste/dto/response/ZeroWasteResultResponse.java
  src/main/java/dorakdorak/domain/zeroWaste/service/ZeroWasteServiceImpl.java
  src/main/java/dorakdorak/global/error/ErrorCode.java
Labels: ✨ Feature

#135 쿼리 수정 후 배포
  src/main/resources/mapper/AdminMapper.xml
Labels: 🌏 Deploy
